### ISSUE TITLE
Multi Module setup not importing the preview

### ISSUE THREAD

**Issue by luismierez** [airbnb/Showkase#225]
Hello, I'm trying to setup showkase in with multiple modules. It's a pretty straightforward set up, we have our main app module that includes our `ui-component` module. We created another app called design catalog and it also include the same `ui-component` there. This is all working fine for us.

The previews live in the `ui-component` module and I want to start the showkase activity in the design catalog app, so I added the `@ShowkaseRoot` in the design catalog app. 

The error I'm running into is that the `RootModuleCodeGen` finds the preview function that I annotated with `@ShowkaseComposable` but it doesn't import it

This is what it generates. It's missing the `import PrimaryButtonPreview` 
```
// This is an auto-generated file. Please do not edit/modify this file.
package com.composeplayground

import androidx.compose.runtime.Composable
import com.airbnb.android.showkase.`annotation`.ShowkaseRootCodegen
import com.airbnb.android.showkase.models.ShowkaseBrowserColor
import com.airbnb.android.showkase.models.ShowkaseBrowserComponent
import com.airbnb.android.showkase.models.ShowkaseBrowserTypography
import com.airbnb.android.showkase.models.ShowkaseProvider
import kotlin.collections.List

@ShowkaseRootCodegen(
  numComposablesWithoutPreviewParameter = 2,
  numComposablesWithPreviewParameter = 0,
  numColors = 0,
  numTypography = 0
)
public class RootModuleCodegen : ShowkaseProvider {
  public val componentList: List<ShowkaseBrowserComponent> =
      mutableListOf<ShowkaseBrowserComponent>(
        ShowkaseBrowserComponent(
            group = "Default Group",
            componentName = "JustAPreview",
            componentKDoc = "",
            componentKey =
                """com.composeplayground_null_DefaultGroup_JustAPreview_null""",
            isDefaultStyle = false,
            component = @Composable { JustAPreview() }),
        ShowkaseBrowserComponent(
            group = "Default Group",
            componentName = "PrimaryButtonPreview",
            componentKDoc = "",
            componentKey = """_null_DefaultGroup_PrimaryButtonPreview_""",
            isDefaultStyle = false,
            styleName = "",
            component = @Composable { PrimaryButtonPreview() }) // this throws an error
      )

  public val colorList: List<ShowkaseBrowserColor> = listOf<ShowkaseBrowserColor>()

  public val typographyList: List<ShowkaseBrowserTypography> = listOf<ShowkaseBrowserTypography>()

  public override fun getShowkaseComponents() = componentList

  public override fun getShowkaseColors() = colorList

  public override fun getShowkaseTypography() = typographyList
}
```

If I move the `@ShowkaseComposable` annotated preview to the design catalog module then it works fine. Any ideas as to what I might be doing wrong?

I've added the showkase import to both the `ui-components` module and the design catalog app module. Let me know if I can provide more info. Thanks!

**Comment by vinaygaba** [comment]
@luismierez Can you try again! I think there was a bug that has been fixed since the last few release. I apologize for not responding earlier.

**Comment by francescocervone** [comment]
Hi @vinaygaba. It's still happening with 1.0.0-beta14. Different project but same configuration.
